inventory/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns('',
    url(r'^$', 'inventory.views.dashboard'),
    url(r'^locations', 'inventory.views.inventory_index'),
    url(r'^parts', 'inventory.views.inventory_index_parts'),
    url(r'^new_count/$', 'inventory.views.new_count'),
    url(r'^part/(?P<part_number>\.+)$', 'inventory.views.part'),
    url(r'^audit/(?P<scan_id>\d+)$', 'inventory.views.switch_audit'),
    url(r'^location_labels/$', 'pdfgen.location_labels.location_labels'),
    url(r'^location_scan_sheet/$', 'pdfgen.location_scan_sheet.location_scan_sheet'),
    url(r'^location/(?P<location_code>.+)$', 'inventory.views.location'),
    url(r'^part/(?P<part_number>.+)$', 'inventory.views.part_inv'),
    url(r'^scansexport/$', 'inventory.views.export_scans'),
    url(r'^deletescans/$', 'inventory.views.delete_scans'),

    url(r'^ajax/location/$', 'inventory.ajax.location_ajax'),

)

mtr/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
admin.autodiscover()

# Uncomment the next two lines to enable the admin:
    # from django.contrib import admin
    # admin.autodiscover()

urlpatterns = patterns('',
                       url(r'^$', 'dashboard.views.home', name='home'),
                       url(r'^reports/', include('reports.urls')),
                       url(r'^documents/', include('documents.urls')),
                       url(r'^orders/', include('orders.urls')),
                       url(r'^search/', include('search.urls')),
                       url(r'^parts/', include('parts.urls')),
                       url(r'^vendors/', include('vendors.urls')),
                       url(r'^inventory/', include('inventory.urls')),

                       url('^accounts/', include('django.contrib.auth.urls')),
                       url('^activity/', include('actstream.urls')),
                       url(r'^select2/', include('django_select2.urls')),

                       # Admin related urls
                       (r'^admin/doc/', include('django.contrib.admindocs.urls')),
                       url(r'^admin/', include(admin.site.urls)),
                       url(r'^djangojs/', include('djangojs.urls')),
                      )

parts/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns('',
    url(r'^$', 'parts.views.parts_index', name='parts_index'),
    url(r'^new_part/$', 'parts.views.new_part'),
    url(r'^label/$', 'parts.views.part_label'),
    url(r'^show_label/(?P<part_number>.+)/$', 'pdfgen.part_label.part_label'),
    url(r'^edit/(?P<part_number>.+)/$', 'parts.views.edit_part'),
    url(r'^import_stocking/$', 'parts.views.import_stocking_cost'),   
    url(r'^(?P<part_number>.+)/$', 'parts.views.part'),


)

dashboard/models.py
from django.db import models
from django.contrib.auth.models import User

class NewsItem(models.Model):
    title = models.CharField(max_length=256)
    news = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User)
    
    def __unicode__(self):
        return self.title

inventory/models.py
from django.db import models
from parts.models import Part
from django.db.models import Avg, Sum
from django.contrib.auth.models import User

class InventoryLocation(models.Model):
    location_code = models.CharField(max_length=32, unique=True)
    count_complete = models.BooleanField(default=False)
    
    class Meta:
        ordering = ['location_code']
    
    def __unicode__(self):
        return str(self.location_code)
        
    def check_audits(self):
        no_audit = InventoryCount.objects.filter(location=self, audited=False).count()
        if no_audit > 0:
            return False
        else:
            return True
    
    def scan_count(self):
        return InventoryCount.objects.filter(location=self).count()
        
    def scan_value(self):
        agg = InventoryCount.objects.filter(location=self).aggregate(stocking_value=Sum('stocking_value'), total_parts=Sum('inventory_count'))
        return agg['stocking_value']
        
    @models.permalink
    def get_absolute_url(self):
        return ('inventory.views.location', [str(self.location_code)])
        
    
class InventoryCount(models.Model):
    part = models.ForeignKey(Part)
    location = models.ForeignKey(InventoryLocation)
    inventory_count = models.IntegerField(null=True)
    count_timestamp = models.DateTimeField(auto_now_add=True)
    counter = models.ForeignKey(User, related_name='count_user', null=True)
    scans = models.IntegerField(null=True)
    audited = models.BooleanField(default=False)
    auditor = models.ForeignKey(User, null=True, related_name='audit_user')
    audit_timestamp = models.DateTimeField(null=True)
    stocking_value = models.DecimalField(null=True, decimal_places=4,
                                         max_digits=12)
    
    class Meta:
        ordering = ['part']

    def save(self, *args, **kwargs):
        self.stocking_value = self.get_scan_value()
        super(InventoryCount, self).save(*args, **kwargs)
    
    def __unicode__(self):
        return "%s: %s pcs" % (self.part, self.inventory_count)

    def get_scan_value(self):
        try:
            cost = PartValuation.objects.get(part=self.part)
            value = self.inventory_count * cost.stocking_cost
        except:
            value = 0
        return value
        
    def get_combined_part_count(self):
        parts = InventoryCount.objects.filter(part=self.part).aggregate(total_count=Sum('inventory_count'))
        return parts['total_count']
        
    def get_combined_inventory_value(self):
        parts = InventoryCount.objects.filter(part=self.part).aggregate(value=Sum('stocking_value'))
        return parts['value']
        
    def get_pre_inventory_count(self):
        part = PartValuation.objects.get(part=self.part)
        return part.quantity
        
    def get_pre_inventory_value(self):
        part = PartValuation.objects.get(part=self.part)
        return part.ext_value
    
    def get_applied_quantity(self):
        part = PartValuation.objects.get(part=self.part)
        return part.applied_quantity
        
    def get_difference(self):
        post = self.get_combined_part_count()
        pre = self.get_pre_inventory_count()
        return post - pre
        
    def get_dollar_difference(self):
        post = self.get_combined_inventory_value()
        pre = self.get_pre_inventory_value()
        
        return post - pre
        
    def get_on_reserve(self):
        pv = PartValuation.objects.get(part=self.part)
        return pv.applied_quantity
    
    def get_less_reserve(self):
        return self.inventory_count - self.get_on_reserve()
        
        
        
        
class PartValuation(models.Model):
    part = models.ForeignKey(Part, unique=True)
    uom = models.CharField(max_length=4, null=True)
    date = models.DateTimeField(auto_now_add=True)
    quantity = models.IntegerField(null=True)
    applied_quantity = models.IntegerField(null=True, default=0)
    stocking_cost = models.DecimalField(decimal_places=4, max_digits=12, null=True)
    ext_value = models.DecimalField(null=True, decimal_places=4, max_digits=12)
    
    class Meta:
        ordering = ['part']
    
    def __unicode__(self):
        return "%s (pcs: %s)" % (self.part.part_number, self.quantity)
    
class InventoryValuation(models.Model):
    date = models.DateTimeField(auto_now_add=True)
    total_parts = models.IntegerField()
    total_valuation = models.DecimalField(decimal_places=4, max_digits=16)
    

inventory/forms.py
from django import forms
from django.forms import ModelForm
from parts.models import Part
from vendors.models import Vendor
from django_select2 import *
from inventory.models import InventoryCount, InventoryLocation
    
class PartChoice(AutoModelSelect2Field):
    queryset = Part.objects
    search_fields = ['part_number__istartswith',]
    
class LocationChoice(AutoModelSelect2Field):
    queryset = InventoryLocation.objects
    search_fields = ['location_code__istartswith',]
    
class InventoryForm(forms.Form):
    part = forms.CharField()
    location = forms.CharField()
    inventory_count = forms.IntegerField()
    location_complete = forms.BooleanField(required=False)
    
class DirectToLocationForm(forms.Form):
    location = LocationChoice()
    
class DirectToPartForm(forms.Form):
    part = PartChoice()

parts/forms.py
from django import forms
from django.forms import ModelForm
from parts.models import Part
from vendors.models import Vendor
from django_select2 import *

class PartChoice(AutoModelSelect2Field):
    queryset = Part.objects
    search_fields = ['part_number__istartswith',]
    max_results = 10

class NewPartForm(ModelForm):

    def __init__(self, *args, **kwargs):
        super(NewPartForm, self).__init__(*args, **kwargs)
        self.fields['alternate_number'].required = False

    class Meta:
        model = Part
        fields = ['part_number', 'alternate_number', 'specification', 'description', 'box_quantity',]

class PartLabelForm(forms.Form):
    part_number = PartChoice()

class StockingCostCSVForm(forms.Form):
    file = forms.FileField()

dashboard/views.py
from django.shortcuts import render_to_response, get_object_or_404
from django.template import RequestContext

from documents.models import Document
from orders.models import Order
from parts.models import Part
from reports.models import Report
from dashboard.models import NewsItem

from actstream import action
from actstream.models import model_stream
from mtr import graph_utils

import datetime


def home(request):
    date = datetime.datetime.today() - datetime.timedelta(days=30)
    documents = Document.objects.all().count()
    reports = Report.objects.all().count()
    orders = Order.objects.all().count()
    parts = Part.objects.all().count()
    log = model_stream(request.user)[:8]
    news = NewsItem.objects.all().order_by('-date')[:5]
    
    data = Report.objects.filter(created_at__gte=date)
    r_graph = graph_utils.flot_values(data)
    
    data = Document.objects.filter(created_at__gte=date)
    d_graph = graph_utils.flot_values(data)
    
    data = Order.objects.filter(created_at__gte=date)
    o_graph = graph_utils.flot_values(data)
    
    data = Part.objects.filter(created_at__gte=date)
    p_graph = graph_utils.flot_values(data)
    
    return render_to_response('dashboard/home.html', 
                              {
                                  'doc_count': documents,
                                  'report_count': reports,
                                  'order_count': orders,
                                  'part_count': parts,
                                  'log': log,
                                  'news': news,
                                  'report_graph': r_graph,
                                  'document_graph': d_graph,
                                  'order_graph': o_graph,
                                  'part_graph': p_graph,
                              },
                              context_instance=RequestContext(request))

parts/views.py
from django.contrib import messages
from django.core.mail import EmailMessage
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect, HttpResponsePermanentRedirect, HttpResponse
from django.shortcuts import render_to_response, redirect, get_object_or_404
from django.template import RequestContext
from actstream import action
from pure_pagination import Paginator, EmptyPage, PageNotAnInteger

from parts.models import Part
from inventory.models import PartValuation
from parts.forms import NewPartForm, PartLabelForm, StockingCostCSVForm
from reports.models import Report

import csv

def parts_index(request):
    parts = Part.objects.all()
    try:
        page = int(request.GET.get('page', '1'))
    except ValueError:
        page = 1

    paginator = Paginator(parts, 25)

    try:
        parts_list = paginator.page(page)
    except (PageNotAnInteger, EmptyPage):
        parts_list = paginator.page(1)

    return render_to_response('parts/parts_index.html',
                              {
                                'parts': parts_list,
                              },
                              context_instance=RequestContext(request))

def part(request, part_number):
    part = Part.objects.get(part_number=part_number)
    reports = Report.objects.filter(part_number=part)
    return render_to_response('parts/part.html',
                              {'part': part,
                               'reports': reports,
                              },
                              context_instance=RequestContext(request))

def part_label(request):
    form = PartLabelForm(request.POST)
    if form.is_valid():
        return HttpResponseRedirect(reverse('pdfgen.part_label.part_label', kwargs={'part_number': form.cleaned_data['part_number']}))
    else:
        return render_to_response('parts/part_label.html',
                              {'form': form,},
                              context_instance=RequestContext(request))

def new_part(request):
    if request.method == 'POST':
        partform = NewPartForm(request.POST)
        if partform.is_valid():
            part = partform.save()
            part.created_by = request.user
            part.save()
            action.send(request.user, verb="created part", target=part)
            return HttpResponseRedirect(part.get_absolute_url())
    else:
        partform = NewPartForm()
    return render_to_response('parts/new_part.html',
                              {'partform': partform,},
                              context_instance=RequestContext(request))

def import_stocking_cost(request):
    if request.method == 'POST':
        form = StockingCostCSVForm(request.POST, request.FILES)
        if form.is_valid():
            invreader = csv.reader(request.FILES['file'], delimiter=',')
            not_found = []
            sum = 0
            PartValuation.objects.all().delete()
            for row in invreader:
                part_number = row[0].strip().upper()
                uom = row[1].strip().upper()
                applied = row[2].replace(",","")
                on_hand = row[3].replace(",","")
                stocking_cost = row[4].strip().replace(",","")
                #self.stdout.write("PART: %s | QTY: %s | COST: %s" % (part_number, on_hand, stocking_cost))

                try:
                    part = Part.objects.get(part_number=part_number)
                    v, created = PartValuation.objects.get_or_create(part=part)
                    v.uom = uom
                    v.quantity = on_hand
                    v.stocking_cost = stocking_cost
                    v.ext_value = float(v.stocking_cost) * float(v.quantity)
                    v.applied_quantity = applied
                    #self.stdout.write("PART: %s | QTY: %s | COST: %s | EXT: %s" % (v.part.part_number, v.quantity, v.stocking_cost, v.ext_value))
                    v.save()
                    sum += v.ext_value
                except:
                    not_found.append(part_number)

            #self.stdout.write("\n\nPARTS NOT FOUND: ")
            #print not_found
            #self.stdout.write("\n\nValuation: %s" % sum)
            messages.success(request, 'Import Successful')
            return HttpResponseRedirect(reverse('inventory.views.dashboard'))
        else:
            messages.success(request, 'Import NOT Successful')
            return HttpResponseRedirect(reverse('inventory.views.dashboard'))


    #self.stdout.write("\nFinished.\n")

def edit_part(request, part_number):
    p = Part.objects.get(part_number=part_number)
    if request.method == 'POST':
        partform = NewPartForm(request.POST, instance=p)
        if partform.is_valid():
            part = partform.save()
            part.created_by = request.user
            part.save()
            action.send(request.user, verb="edited part", target=part)
            return HttpResponseRedirect(part.get_absolute_url())
    else:
        partform = NewPartForm(instance=p)
    return render_to_response('parts/new_part.html',
                              {'partform': partform,},
                              context_instance=RequestContext(request))

templates/inventory/inventory_index_locations.html
{% extends "base/main.html" %}
{% load thumbnail %}

{% block head %}
<script src="{{ STATIC_URL }}js/jquery.dataTables.min.js"></script>
<script src="{{ STATIC_URL }}js/unicorn.tables.js"></script>
{% endblock %}

{% block inventory_active %}active open{% endblock %}

{% block breadcrumb_links %}
    <a href="#" class="current">Inventory Index</a>
{% endblock %}

{% block page_title %}Browse Locations{% endblock %}
{% block title %}Browse Locations{% endblock %}


{% block content %}
<div class="row-fluid">
    <div class="span6">
        <form class="form-horizontal" action="" method="post" autocomplete="off">
            {% csrf_token %}
            <div class="control-group">
                <label class="control-label" for="id_company">Jump Direct To Location</label>
                <div class="controls">
                    {% for field in direct_to_location_form %}
                    {{ field }}
                    {% endfor %}
                    &nbsp;
                    <button type="submit" name="save" class="btn btn-inverse">Go</button>
                    <input type="hidden" name="jump" value="location" />

                </div>
            </div>
        </form>
    </div>
    <div class="span6">
        <form class="form-horizontal" action="" method="post" autocomplete="off">
            {% csrf_token %}
            <div class="control-group">
                <label class="control-label" for="id_company">Jump Direct To Part</label>
                <div class="controls">
                    {% for field in direct_to_part_form %}
                    {{ field }}
                    {% endfor %}
                    &nbsp;
                    <button type="submit" name="save" class="btn btn-inverse">Go</button>
                    <input type="hidden" name="jump" value="part" />
                </div>
            </div>
        </form>
    </div>
</div>

<div class="row-fluid">
    <div class="span12">
        <div class="widget-box">
            <div class="widget-title">
                <span class="icon">
                    <i class="icon-th"></i>
                </span>
                <h5>Location Index</h5>
            </div>
            <div class="widget-content nopadding">
                <table class="table table-bordered data-table">
                    <thead>
                        <tr>
                            <th>Rack Location</th>
                            <th># of Scans</th>
                            <th>Fully Audited?</th>
                            <th>Scan Value</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for l in locations %}
                        <tr>
                            <td>
                                <a href="{{ l.get_absolute_url }}">{{ l.location_code }}</a>
                            </td>
                            <td>
                                {{ l.scan_count }}
                            </td>
                            <td>
                                {{ l.check_audits }}
                            </td>
                            <td>
                                ${{ l.scan_value|default:"0" }}
                            </td>


                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/inventory/location.html
{% extends "base/main.html" %}

{% load thumbnail %}
{% load humanize %}

{% block title %}
Location {{ location }}
{% endblock %}


{% block inventory_active %}active open{% endblock %}

{% block breadcrumb_links %}
<a href="{% url 'inventory.views.inventory_index' %}">Inventory</a>
<a class="current">{{ location }}</a>
{% endblock %}

{% block page_title %}Location {{ location }} Details{% endblock %}


{% block head %}
<script src="{{ STATIC_URL }}js/jquery.dataTables.min.js"></script>
<script src="{{ STATIC_URL }}js/unicorn.tables.js"></script>
<link rel="stylesheet" href="{{ STATIC_URL }}css/uniform.css" type="text/css" media="screen" />
<script src="{{ STATIC_URL }}js/jquery.uniform.js"></script>
<link href="{{ STATIC_URL }}css/select2.css" rel="stylesheet" />
<script src="http://ivaynberg.github.com/select2/select2-master/select2.js"></script>
<script src="{{ STATIC_URL }}js/jquery.validate.js"></script>
<script src="{{ STATIC_URL }}js/unicorn.form_validation.js"></script>
<link rel="stylesheet" href="{{ STATIC_URL }}js/fancybox/jquery.fancybox.css" type="text/css" media="screen" />
<script src="{{ STATIC_URL }}js/fancybox/jquery.fancybox.pack.js"></script>
<link href="{{ STATIC_URL }}css/bootstrap-editable.css" rel="stylesheet">
<script src="{{ STATIC_URL }}js/bootstrap-editable.min.js"></script>

<script type="text/javascript">
    $(document).on("click", ".open-email-doc-modal", function () {
            var id = $(this).data('id');
     $("#doc-id-hidden").val( id );
     $('#email_document-modal').modal('show');
     console.log('Show Modal');
});
</script>

    
{% endblock %}



{% block content %}
<div class="row-fluid">
    <div class="span6">
        <div class="widget-box collapsible">
            <div class="widget-title">
            <a href="#attributes" data-toggle="collapse">
                <span class="icon">
                    <i class="icon-list-alt"></i>
                </span>
                <h5>Location Statistics</h5>
            </a>
            </div>
            <div class="widget-content nopadding">
                <table class="table table-bordered">
                    <tr>
                        <th></th>
                        <th>Part Numbers Scanned</th>
                        <th>Total # of Parts</th>
                        <th>Scanned Inventory Value</th>
                    </tr>
                    <tr>
                        <th>Scan Overview</th>
                        <td>{{ total_part_numbers }}</td>
                        <td>{{ agg.total_parts }}</td>
                        <td>${{ agg.stocking_value }}</td>
                    </tr>
                </table>
            </div>
        </div>
    </div>
</div>

<div class="row-fluid">
    <div class="span12">
        <div class="widget-box collapsible">
            <div class="widget-title">
            <a href="#attributes" data-toggle="collapse">
                <span class="icon">
                    <i class="icon-list-alt"></i>
                </span>
                <h5>Counts in location {{ location }}</h5>
            </a>
            </div>
            <div class="widget-content nopadding">
                <table class="table table-bordered">
                    <tr>
                        <th>Tools</th>
                        <th>Part #</th>
                        <th><strong>Count</strong></th>
                        <th>On Reserve</th>
                        <th>Count less Reserve</th>
                        <th>Stocking Cost/UOM</th>
                        <th>Scan Value</th>
                        <th>Scan Time</th>
                        <th># Scans</th>
                        <th>Counter</th>
                        <th>Audited?</th>
                        <th>Auditor</th>
                    </tr>
                    {% for scan in location.inventorycount_set.all %}
                        <tr id="scan_{{ scan.pk }}">
                            {% include 'inventory/scan_row.html' %}
                        </tr>
                    {% endfor %}
                    <script>
                        $(".audit").live('click', function() {
                            var $id = $(this).data('id');
                                $.ajax({
                                    url: "/inventory/audit/" + $id,
                                    success: function(response) {
                                        $("#scan_"+$id).hide().html(response).fadeIn("fast");
                                    }
                                });
                        });
                    </script>
                        
                </table>
            </div>
        </div>                                               
    </div>
</div>


<div id="modals">
    {% csrf_token %}
    {% include 'modals/attach_document.html' %}
</div>

{% endblock %}

templates/inventory/new_count.html
{% extends "base/main.html" %}
{% block head %}
<link rel="stylesheet" href="{{ STATIC_URL }}css/uniform.css" type="text/css" media="screen" />
<link href="{{ STATIC_URL }}css/select2.css" rel="stylesheet" />
<!-- search typeahead -->
<script type="text/javascript">
    $(document).ready(function() {
        $(".company-ta input[type=text]").typeahead({
            items: 5,
            source: function (query, process) {
                $.get('/search/autocomplete?type=company', { q: query }, function (data) {
                    process(data)
                })
            }
        });
    });
</script>
{% endblock %}

{% block js %}
<script src="{{ STATIC_URL }}js/jquery.uniform.js"></script>
<script src="http://ivaynberg.github.com/select2/select2-master/select2.js"></script>
<script src="{{ STATIC_URL }}js/jquery.validate.js"></script>
<script src="{{ STATIC_URL }}js/unicorn.form_validation.js"></script>
<script type="text/javascript">
    $(document).ready(function() { 
            $("select").select2({ width: 'resolve' });           
            }); 
</script>
{% endblock %}

{% block breadcrumb_links %}
<a href="{% url 'inventory.views.inventory_index' %}">Inventory</a>
<a href="#" class="current">New Inventory Count</a>
{% endblock %}

{% block right_buttons %}{% endblock %}

{% block inventory_active %}active open{% endblock %}

{% block page_title %}New Inventory Count{% endblock %}

{% block content %}
<div class="row-fluid">
    <div class="span7">
        <div class="widget-box">
            <div class="widget-title">
                <span class="icon">
                    <i class="icon-th"></i>
                </span>
                <h5>Insert inventory count</h5>
            </div>
            <div class="widget-content nopadding">
                <form id="count_form" class="well form-horizontal" action="" method="post" autocomplete="off">
                    {% csrf_token %}
                    
                    <div class="control-group">
                        {% for field in inventoryform %}
                        <label class="control-label" for="id_company">{{ field.label }}</label>                        
                        <div class="controls">
                            {{ field.errors }}
                            {{ field }}
                            <span class="help-block">{{ field.help_text }}</span>
                        </div>
                        {% endfor %}
                    </div>

                    <div class="form-actions">
                        <button type="submit" name="save" class="btn btn-inverse">Save Count</button>
                        <input type="button" class="btn btn-default" onclick="formReset()" value="Clear Form">
                        <script>
                            function formReset()
                            {
                                document.getElementById("count_form").reset();
                            }
                        </script>
                        <script>
                            $("#id_location").focusout(function () {
                                var $form = $("#count_form")
                                var $inputs = $form.find("input, select, button, textarea");
                                var serializedData = $form.serialize();
                                $.ajax({ // create an AJAX call...
                                    data: serializedData, // get the form data
                                    type: $(this).attr('method'), // GET or POST
                                    url: "/inventory/ajax/location/", // the file to call
                                    success: function(response) { // on success..
                                        $("#location_box").hide().html(response).fadeIn("slow");
                                    }
                                });
                            });
                        </script>
                    </div>
                </form>
            </div>
        </div>
    </div>

    <div class="span5">
        <div class="widget-box">
            <div class="widget-title">
                <span class="icon">
                    <i class="icon-th"></i>
                </span>
                <h5>Location Details</h5>
            </div>
            <div class="widget-content" id="location_box">
                Please scan a part number and location to see details.    
            </div>
        </div>
    </div>

    <div class="span5">
        <div class="widget-box">
            <div class="widget-title">
                <span class="icon">
                    <i class="icon-th"></i>
                </span>
                <h5>Recent Counts</h5>
            </div>
            <div class="widget-content">
            {% for r in recent_counts %}
            <li>{{ r.counter }} counted <strong>{{ r.inventory_count }}</strong> pieces of <strong><a href="{{ r.part.get_absolute_url}}">{{ r.part }}</a></strong> in location <strong><a href="{{ r.location.get_absolute_url }}">{{ r.location }}</a></strong></li>
            {% endfor %}   
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    window.onload = function() {
        var input = document.getElementById("id_part").focus();
    }
</script>
{% endblock %}

templates/inventory/scan_row.html
    <td style="text-align:center;">
        {% if scan.audited == True %}
            <a data-id="{{ scan.pk }}" class="btn btn-mini btn-danger audit">Un-Audit</a>
        {% else %}
            <a data-id="{{ scan.pk }}" class="btn btn-mini btn-success audit">Audit</a>
        {% endif %}
    </td>
    {% if part %}
    <td><strong><a href="{{ scan.location.get_absolute_url }}">{{ scan.location }}</a></strong></td>
    {% else %}
        <td><strong><a href="{% url 'inventory.views.part_inv' part_number=scan.part.part_number %}">{{ scan.part }}</a></strong></td>
    {% endif %}
        

    <td><strong>{{ scan.inventory_count }}</strong></td>
    <td>{{ scan.get_on_reserve }}</td>
    <td>{{ scan.get_less_reserve }}</td>
    <td>${{ scan.part.get_stocking_cost }}/{{ scan.part.get_uom }}</td>
    <td>${{ scan.get_scan_value }}</td>
    <td>{{ scan.count_timestamp }}</td>
    <td>{{ scan.scans }}</td>
    <td>{{ scan.counter }}</td>
    <td>{{ scan.audited }}</td>
    <td>{{ scan.auditor }}</td>