mtr/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
admin.autodiscover()

# Uncomment the next two lines to enable the admin:
    # from django.contrib import admin
    # admin.autodiscover()

urlpatterns = patterns('',
                       url(r'^$', 'dashboard.views.home', name='home'),
                       url(r'^reports/', include('reports.urls')),
                       url(r'^documents/', include('documents.urls')),
                       url(r'^orders/', include('orders.urls')),
                       url(r'^search/', include('search.urls')),
                       url(r'^parts/', include('parts.urls')),
                       url(r'^vendors/', include('vendors.urls')),
                       url(r'^inventory/', include('inventory.urls')),

                       url('^accounts/', include('django.contrib.auth.urls')),
                       url('^activity/', include('actstream.urls')),
                       url(r'^select2/', include('django_select2.urls')),

                       # Admin related urls
                       (r'^admin/doc/', include('django.contrib.admindocs.urls')),
                       url(r'^admin/', include(admin.site.urls)),
                       url(r'^djangojs/', include('djangojs.urls')),
                      )

parts/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns('',
    url(r'^$', 'parts.views.parts_index', name='parts_index'),
    url(r'^new_part/$', 'parts.views.new_part'),
    url(r'^label/$', 'parts.views.part_label'),
    url(r'^show_label/(?P<part_number>.+)/$', 'pdfgen.part_label.part_label'),
    url(r'^edit/(?P<part_number>.+)/$', 'parts.views.edit_part'),
    url(r'^import_stocking/$', 'parts.views.import_stocking_cost'),   
    url(r'^(?P<part_number>.+)/$', 'parts.views.part'),


)

parts/models.py
from django.db import models

from specifications.models import Specification

from audit_log.models.fields import LastUserField
from audit_log.models.managers import AuditLog

class Part(models.Model):
    part_number = models.CharField(max_length=128, unique=True)
    alternate_number = models.CharField(max_length=128, null=True)
    description = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    box_quantity = models.IntegerField(null=True, blank=True)
    specification = models.ForeignKey(Specification, null=True)
    product_code = models.CharField(max_length=16, null=True)
    
    class Meta:
        ordering = ('part_number', )
    
    def __unicode__(self):
        return self.part_number

    def save(self, *args, **kwargs):
        self.part_number = self.part_number.upper()
        self.description = self.description.upper()
        super(Part, self).save(*args, **kwargs)
        
    def get_stocking_cost(self):
        from inventory.models import PartValuation
        cost = PartValuation.objects.get(part=self)
        return cost.stocking_cost

    def get_uom(self):
        from inventory.models import PartValuation
        cost = PartValuation.objects.get(part=self)
        return cost.uom        
    
    @models.permalink
    def get_absolute_url(self):
        return ('parts.views.part', [str(self.part_number)])
        
    @models.permalink
    def get_absolute_inventory_url(self):
        return ('inventory.views.part', [str(self.part_number)])

        

parts/forms.py
from django import forms
from django.forms import ModelForm
from parts.models import Part
from vendors.models import Vendor
from django_select2 import *

class PartChoice(AutoModelSelect2Field):
    queryset = Part.objects
    search_fields = ['part_number__istartswith',]
    max_results = 10

class NewPartForm(ModelForm):

    def __init__(self, *args, **kwargs):
        super(NewPartForm, self).__init__(*args, **kwargs)
        self.fields['alternate_number'].required = False

    class Meta:
        model = Part
        fields = ['part_number', 'alternate_number', 'specification', 'description', 'box_quantity',]

class PartLabelForm(forms.Form):
    part_number = PartChoice()

class StockingCostCSVForm(forms.Form):
    file = forms.FileField()

parts/views.py
from django.contrib import messages
from django.core.mail import EmailMessage
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect, HttpResponsePermanentRedirect, HttpResponse
from django.shortcuts import render_to_response, redirect, get_object_or_404
from django.template import RequestContext
from actstream import action
from pure_pagination import Paginator, EmptyPage, PageNotAnInteger

from parts.models import Part
from inventory.models import PartValuation
from parts.forms import NewPartForm, PartLabelForm, StockingCostCSVForm
from reports.models import Report

import csv

def parts_index(request):
    parts = Part.objects.all()
    try:
        page = int(request.GET.get('page', '1'))
    except ValueError:
        page = 1

    paginator = Paginator(parts, 25)

    try:
        parts_list = paginator.page(page)
    except (PageNotAnInteger, EmptyPage):
        parts_list = paginator.page(1)

    return render_to_response('parts/parts_index.html',
                              {
                                'parts': parts_list,
                              },
                              context_instance=RequestContext(request))

def part(request, part_number):
    part = Part.objects.get(part_number=part_number)
    reports = Report.objects.filter(part_number=part)
    return render_to_response('parts/part.html',
                              {'part': part,
                               'reports': reports,
                              },
                              context_instance=RequestContext(request))

def part_label(request):
    form = PartLabelForm(request.POST)
    if form.is_valid():
        return HttpResponseRedirect(reverse('pdfgen.part_label.part_label', kwargs={'part_number': form.cleaned_data['part_number']}))
    else:
        return render_to_response('parts/part_label.html',
                              {'form': form,},
                              context_instance=RequestContext(request))

def new_part(request):
    if request.method == 'POST':
        partform = NewPartForm(request.POST)
        if partform.is_valid():
            part = partform.save()
            part.created_by = request.user
            part.save()
            action.send(request.user, verb="created part", target=part)
            return HttpResponseRedirect(part.get_absolute_url())
    else:
        partform = NewPartForm()
    return render_to_response('parts/new_part.html',
                              {'partform': partform,},
                              context_instance=RequestContext(request))

def import_stocking_cost(request):
    if request.method == 'POST':
        form = StockingCostCSVForm(request.POST, request.FILES)
        if form.is_valid():
            invreader = csv.reader(request.FILES['file'], delimiter=',')
            not_found = []
            sum = 0
            PartValuation.objects.all().delete()
            for row in invreader:
                part_number = row[0].strip().upper()
                uom = row[1].strip().upper()
                applied = row[2].replace(",","")
                on_hand = row[3].replace(",","")
                stocking_cost = row[4].strip().replace(",","")
                #self.stdout.write("PART: %s | QTY: %s | COST: %s" % (part_number, on_hand, stocking_cost))

                try:
                    part = Part.objects.get(part_number=part_number)
                    v, created = PartValuation.objects.get_or_create(part=part)
                    v.uom = uom
                    v.quantity = on_hand
                    v.stocking_cost = stocking_cost
                    v.ext_value = float(v.stocking_cost) * float(v.quantity)
                    v.applied_quantity = applied
                    #self.stdout.write("PART: %s | QTY: %s | COST: %s | EXT: %s" % (v.part.part_number, v.quantity, v.stocking_cost, v.ext_value))
                    v.save()
                    sum += v.ext_value
                except:
                    not_found.append(part_number)

            #self.stdout.write("\n\nPARTS NOT FOUND: ")
            #print not_found
            #self.stdout.write("\n\nValuation: %s" % sum)
            messages.success(request, 'Import Successful')
            return HttpResponseRedirect(reverse('inventory.views.dashboard'))
        else:
            messages.success(request, 'Import NOT Successful')
            return HttpResponseRedirect(reverse('inventory.views.dashboard'))


    #self.stdout.write("\nFinished.\n")

def edit_part(request, part_number):
    p = Part.objects.get(part_number=part_number)
    if request.method == 'POST':
        partform = NewPartForm(request.POST, instance=p)
        if partform.is_valid():
            part = partform.save()
            part.created_by = request.user
            part.save()
            action.send(request.user, verb="edited part", target=part)
            return HttpResponseRedirect(part.get_absolute_url())
    else:
        partform = NewPartForm(instance=p)
    return render_to_response('parts/new_part.html',
                              {'partform': partform,},
                              context_instance=RequestContext(request))

templates/parts/new_part.html
{% extends "base/main.html" %}
{% block head %}
<link rel="stylesheet" href="{{ STATIC_URL }}css/uniform.css" type="text/css" media="screen" />
<link href="{{ STATIC_URL }}css/select2.css" rel="stylesheet" />
<!-- search typeahead -->
<script type="text/javascript">
    $(document).ready(function() {
        $(".company-ta input[type=text]").typeahead({
            items: 5,
            source: function (query, process) {
                $.get('/search/autocomplete?type=company', { q: query }, function (data) {
                    process(data)
                })
            }
        });
    });
</script>
{% endblock %}

{% block js %}
<script src="{{ STATIC_URL }}js/jquery.uniform.js"></script>
<script src="http://ivaynberg.github.com/select2/select2-master/select2.js"></script>
<script src="{{ STATIC_URL }}js/jquery.validate.js"></script>
<script src="{{ STATIC_URL }}js/unicorn.form_validation.js"></script>
<script type="text/javascript">
    $(document).ready(function() { 
            $("select").select2({ width: 'resolve' });           
            }); 
</script>
{% endblock %}

{% block breadcrumb_links %}
<a href="{% url 'parts.views.parts_index' %}">Parts</a>
<a href="#" class="current">Add/Edit Part</a>
{% endblock %}

{% block right_buttons %}{% endblock %}

{% block parts_active %}active open{% endblock %}

{% block page_title %}Add/Edit a part{% endblock %}

{% block content %}
<div class="row-fluid">
    <div class="span7">
        <div class="widget-box">
            <div class="widget-title">
                <span class="icon">
                    <i class="icon-th"></i>
                </span>
                <h5>Add a new part</h5>
            </div>
            <div class="widget-content nopadding">
                <form class="well form-horizontal" action="" method="post" autocomplete="off">
                    {% csrf_token %}
                    
                    <div class="control-group">
                        {% for field in partform %}
                        <label class="control-label" for="id_company">{{ field.label }}</label>                        
                        <div class="controls">
                            {{ field.errors }}
                            {{ field }}
                            <span class="help-block">{{ field.help_text }}</span>
                        </div>
                        {% endfor %}
                    </div>

                    <div class="form-actions">
                        <button type="submit" class="btn btn-inverse">Save Part</button>
                        <button type="submit" class="btn btn-default" onclick="this.form.reset()">Clear Form</button>
                    </div>
                </form>
            </div>
        </div>
    </div>


    <div class="span5">
        <div class="widget-box">
            <div class="widget-title">
                <span class="icon">
                    <i class="icon-th"></i>
                </span>
                <h5>New Part Checklist</h5>
            </div>
            <div class="widget-content">
               
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/parts/part.html
{% extends "base/main.html" %}

{% load thumbnail %}
{% load humanize %}

{% block title %}
Part # {{ part.part_number }}
{% endblock %}


{% block parts_active %}active open{% endblock %}

{% block breadcrumb_links %}
<a href="{% url 'parts_index' %}">Parts</a>
<a class="current">{{ part }} : {{ part.description }}</a>
{% endblock %}

{% block page_title %}Part # {{ part.part_number }} Details{% endblock %}


{% block head %}
<script src="{{ STATIC_URL }}js/jquery.dataTables.min.js"></script>
<script src="{{ STATIC_URL }}js/unicorn.tables.js"></script>
<link rel="stylesheet" href="{{ STATIC_URL }}css/uniform.css" type="text/css" media="screen" />
<script src="{{ STATIC_URL }}js/jquery.uniform.js"></script>
<link href="{{ STATIC_URL }}css/select2.css" rel="stylesheet" />
<script src="http://ivaynberg.github.com/select2/select2-master/select2.js"></script>
<script src="{{ STATIC_URL }}js/jquery.validate.js"></script>
<script src="{{ STATIC_URL }}js/unicorn.form_validation.js"></script>
<link rel="stylesheet" href="{{ STATIC_URL }}js/fancybox/jquery.fancybox.css" type="text/css" media="screen" />
<script src="{{ STATIC_URL }}js/fancybox/jquery.fancybox.pack.js"></script>
<link href="{{ STATIC_URL }}css/bootstrap-editable.css" rel="stylesheet">
<script src="{{ STATIC_URL }}js/bootstrap-editable.min.js"></script>

<script type="text/javascript">
    $(document).on("click", ".open-email-doc-modal", function () {
            var id = $(this).data('id');
     $("#doc-id-hidden").val( id );
     $('#email_document-modal').modal('show');
     console.log('Show Modal');
});
</script>

    
{% endblock %}



{% block content %}
<div class="row-fluid">
    <div class="span12">
        <h2>Part # {{ part.part_number }} <small>{{ part.description }}</small></h2>   
    </div>   
</div>

<div class="row-fluid">
    <div class="span7">
        <div class="widget-box collapsible">
            <div class="widget-title">
            <a href="#attributes" data-toggle="collapse">
                <span class="icon">
                    <i class="icon-list-alt"></i>
                </span>
                <h5>Lot #'s associated with this part</h5>
            </a>
            </div>
            <div class="widget-content nopadding">
                <table class="table table-bordered">
                    <tr>
                        <th>Lot #</th>
                        <th>Vendor</th>
                        <th>PO #</th>
                        <th>Date</th>
                    </tr>
                    {% for report in reports %}
                    <tr>
                        <td><strong><a href="{{ report.get_absolute_url }}">{{ report.lot_number }}</a></strong></td>
                        <td><a href="{{ report.vendor.get_absolute_url }}">{{ report.vendor.name }}</a></td>
                        <td>
                            {% if report.origin_po %}
                            {% with po_list=report.po_list %}
                            {% include 'base/po_list.html' %}
                            {% endwith %}
                            {% else %}
                            N/A
                            {% endif %}
                        </td>
                        <td>{{ report.created_at }}</td>
                    </tr>
                    {% endfor %}
                </table>
            </div>
        </div>                                               
    </div>

    <div class="span5">
        <div class="span12">
            <div class="widget-box">
                <div class="widget-title">
                    <span class="icon">
                        <i class="icon-random"></i>
                    </span>
                    <h5>Details</h5>
                    <div class="buttons">
                        <a class="btn btn-inverse btn-mini tip-left" title="Edit Part" href="{% url 'parts.views.edit_part' part.part_number %}" data-toggle="modal"><i class="icon-edit icon-white"></i></a>
                    </div>
                    </div>
                    <div class="widget-content nopadding">
                        <table class="table table-bordered">
                            <tr>
                                <td>Part #</td>
                                <td>{{ part }}</td>
                            </tr>
                            <tr>
                                <td>Specification #</td>
                                <td>{{ part.specification }}</td>
                            </tr>
                            <tr>
                                <td>Description</td>
                                <td>{{ part.description }}</td>
                            </tr>
                            <tr>
                                <td>Box Qty</td>
                                <td>{{ part.box_quantity|default:"N/A" }}</td>
                            </tr>
                            <tr>
                                <td>Created</td>
                                <td>{{ part.created_at }}</td>
                            </tr>
                            <tr>
                                <td>Last Update</td>
                                <td>{{ part.updated_at }}</td>
                            </tr>
                        </table>
                    </div>
                </div>
            </div>
       
        <!-- Audit Log -->
        <div>
            <div class="widget-box">
                <div class="widget-title">
                    <span class="icon">
                        <i class="icon-random"></i>
                    </span>
                    <h5>Audit Log</h5>
                </div>
                <div class="widget-content">
                    <ul class="activity-list">
                        {% for l in audit_log %}
                        <li><a href="#">
                            <i class="icon-user"></i>
                            <strong>{{ l.action_user }}</strong> {{ l.get_action_type_display|lower }} {{ l.object_state }} {{ l.object }}<span>{{ l.action_date|naturaltime }}</span>
    
                        </a></li>
                        {% endfor %}
                    </ul>
                </div>
            </div>    
        </div>
    </div>
</div>

<div id="modals">
    {% csrf_token %}
    {% include 'modals/attach_document.html' %}
</div>

{% endblock %}

templates/parts/part_label.html
{% extends "base/main.html" %}
{% block head %}
<link rel="stylesheet" href="{{ STATIC_URL }}css/uniform.css" type="text/css" media="screen" />
<link href="{{ STATIC_URL }}css/select2.css" rel="stylesheet" />
<!-- search typeahead -->
<script type="text/javascript">
    $(document).ready(function() {
        $(".company-ta input[type=text]").typeahead({
            items: 5,
            source: function (query, process) {
                $.get('/search/autocomplete?type=company', { q: query }, function (data) {
                    process(data)
                })
            }
        });
    });
</script>
{% endblock %}

{% block js %}
<script src="{{ STATIC_URL }}js/jquery.uniform.js"></script>
<script src="http://ivaynberg.github.com/select2/select2-master/select2.js"></script>
<script src="{{ STATIC_URL }}js/jquery.validate.js"></script>
<script src="{{ STATIC_URL }}js/unicorn.form_validation.js"></script>
<script type="text/javascript">
    $(document).ready(function() { 
            $("select").select2({ width: 'resolve' });           
            }); 
</script>
{% endblock %}

{% block breadcrumb_links %}
<a href="{% url 'parts.views.parts_index' %}">Parts</a>
<a href="#" class="current">Create Part Label</a>
{% endblock %}

{% block right_buttons %}{% endblock %}

{% block parts_active %}active open{% endblock %}

{% block page_title %}Create Part Label{% endblock %}

{% block content %}
<div class="row-fluid">
    <div class="span7">
        <div class="widget-box">
            <div class="widget-title">
                <span class="icon">
                    <i class="icon-th"></i>
                </span>
                <h5>Create Part Label</h5>
            </div>
            <div class="widget-content nopadding">
                <form class="well form-horizontal" action="" method="post" autocomplete="off">
                    {% csrf_token %}
                    {% for field in form %}
                    <div class="control-group">
                        <label class="control-label" for="id_company">{{ field.label }}</label>                        
                        <div class="controls">
                            {{ field }}
                            <span class="help-block">{{ field.help_text }}</span>
                        </div>
                    </div>
                    {% endfor %}
                    <div class="form-actions">
                        <button type="submit" class="btn btn-inverse">Create Label</button>
                    </div>
                </form>
            </div>
            <script type="text/javascript">
            window.onload = function() {
                $('#id_part_number').select2('open');
                $('.controls').prev('.select2-container').find('.select2-input').focus();
            }
</script>
        </div>
    </div>


    <div class="span5">
        <div class="widget-box">
            <div class="widget-title">
                <span class="icon">
                    <i class="icon-th"></i>
                </span>
                <h5>Recent Labels</h5>
            </div>
            <div class="widget-content">
               
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/parts/parts_index.html
{% extends "base/main.html" %}
{% load thumbnail %}

{% block head %}
<script src="{{ STATIC_URL }}js/jquery.dataTables.min.js"></script>
<script src="{{ STATIC_URL }}js/unicorn.tables.js"></script>
{% endblock %}

{% block parts_active %}active open{% endblock %}

{% block breadcrumb_links %}
    <a href="#" class="current">Parts Index</a>
{% endblock %}

{% block page_title %}Browse Parts{% endblock %}
{% block title %}Parts Index{% endblock %}


{% block content %}
<div class="row-fluid">
    <div class="span12">
        <div class="widget-box">
            <div class="widget-title">
                <span class="icon">
                    <i class="icon-th"></i>
                </span>
                <h5>Parts Index</h5>
            </div>
            <div class="widget-content nopadding">
                <table class="table table-bordered">
                    <thead>
                        <tr>
                            <th>Part #</th>
                            <th>Description</th>
                            <th>Created</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for part in parts.object_list %}
                        <tr>
                            
                            <td>
                                <a href="{{ part.get_absolute_url }}">{{ part.part_number }}</a>
                            </td>
                            <td>
                                {{ part.description }}
                            </td>
                            <td>
                                {{ part.created_at }}
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
                {{ parts.render }}
            </div>
        </div>
    </div>
</div>
{% endblock %}